add test api request

diff --git a/.github/actions/shared/verify_installation/action.yml b/.github/actions/shared/verify_installation/action.yml
--- a/.github/actions/shared/verify_installation/action.yml
+++ b/.github/actions/shared/verify_installation/action.yml
@@ -236,8 +236,8 @@ runs:
     - name: Check API response (any status)
       shell: bash
       run: |
-        echo "📡 Sending test request to http://localhost:8080/api/v1/status"
-        curl -v -u user:user http://localhost:8080/api/v1/status || echo "❌ curl failed"
+        echo "📡 Sending test request to http://localhost:8080/api/environments"
+        curl -v -u user:user http://localhost:8080/api/environments || echo "❌ curl failed"
 
       #- name: Run Newman
       #  uses: matt-ball/newman-action@v1
